<template>
  <stormy-nav-group>
    <stormy-nav-item
      name="Dashboard"
      exact
      icon="tabler-icon-gauge"
      color="green"
      count="2"
      href="/"
    />
  </stormy-nav-group>
  <stormy-nav-group>
    <stormy-nav-item
      :disabled="true"
      name="Agenda"
      icon="tabler-icon-calendar-event"
    />
    <stormy-nav-item
      :disabled="true"
      name="Dokumente"
      icon="tabler-icon-folder"
    />
  </stormy-nav-group>
  <stormy-nav-group>
    <stormy-nav-item
      href="/contacts"
      name="Accounts + Kontakte"
      icon="tabler-icon-building-community"
    />
  </stormy-nav-group>
  <stormy-nav-group>
    <stormy-nav-item
      href="/projects"
      name="Projekte"
      icon="tabler-icon-layout-kanban"
    />

    <stormy-nav-item
      :disabled="true"
      name="Verträge"
      icon="tabler-icon-signature"
    />
  </stormy-nav-group>
  <stormy-nav-group>
    <stormy-nav-item
      href="/times"
      name="Zeiten"
      icon="tabler-icon-alarm"
    />
  </stormy-nav-group>
  <stormy-nav-group>
    <stormy-nav-item
      :open="true"
      :animate="true"
      count="2"
      name="Fakturierung + Fibu"
      icon="tabler-icon-file-euro"
    >
      <stormy-sub-nav-item
        :current="true"
        :disabled="true"
        badge="2"
        name="Rechnungen"
        icon="24-bill"
      />
      <stormy-sub-nav-item
        name="Angebote"
        :disabled="true"

        icon="24-bill"
      />
      <stormy-sub-nav-item
        :with-sep="true"
        :disabled="true"
        name="Mahnungen"
        icon="24-bill"
      />
      <stormy-sub-nav-item
        :disabled="true"
        name="Bankkonten"
        icon="24-bill"
      />
      <stormy-sub-nav-item
        :disabled="true"
        name="Ausgaben + Belege"
        icon="24-bill"
      />
    </stormy-nav-item>
  </stormy-nav-group>
</template>
